# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'histogram_demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Masonry' 
  pod 'MJExtension'

  # Pods for histogram_demo

  target 'histogram_demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'histogram_demoUITests' do
    # Pods for testing
  end

end
